### ISSUE TITLE
Error downloading models

### ISSUE THREAD

**Issue by grschneider** [DenOfEquity/PixArt-Sigma-for-webUI#3]
With automatic1111's SD webUI v1.10.0 I get the following error while downloading models:
```
model-00001-of-00002.safetensors: 100%|███████████████████████████████████████████| 9.99G/9.99G [05:14<00:00, 31.7MB/s]
model-00002-of-00002.safetensors: 100%|███████████████████████████████████████████| 9.06G/9.06G [04:42<00:00, 32.1MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [09:58<00:00, 299.03s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:20<00:00, 10.11s/it]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './/models//diffusers//pixart_T5_fp16'. Use `repo_type` argument if needed.
```

Recommended package versions are as follows: 
diffusers==0.29.2
peft==0.12.0
tokenizers==0.19.1
transformers==4.43.3

**Comment by DenOfEquity** [comment]
Thanks for report. Updated.
After downloading the T5 text encoder, ~19GB, OK according to log text, I save locally as fp16, ~9GB, and use this smaller model for all future generations. Problem is down to a recent change to use a device_map, aiming to maximise performance and also allow keeping models loaded. A device_mapped model might be split across CPU and GPU - if so, it turns out that the model save function fails.
I've reworked this download/convert/save part of my code to not use a device_map on the model for the initial download.
Tested by removing my local cache, causing a full redownload/convert/save - worked for me.

**Comment by grschneider** [comment]
Seemingly my initial issue was that an operation related to the fp16 saving failed because accelerate==0.21.0 was unable to move models. Version 0.21.0 was given with requirements_version.txt of my webUI.

After increasing to accelerate==0.25.0 (taken from https://github.com/PixArt-alpha/PixArt-sigma/blob/master/requirements.txt#L4) and your updates everything works now.
Thanks a lot!

**Comment by DenOfEquity** [comment]
Great, I'm glad it's working now.
Accelerate 0.25.0 shouldn't be necessary after my update - my various webUIs are all on 0.21.0 - but it's good to know the upgrade is safe. I'm using a modified diffusers pipeline rather than code directly from the PixArt repo.
