### ISSUE TITLE
Minimum version for diffusers should be 0.29.2

### ISSUE THREAD

**Issue by b-fission** [DenOfEquity/PixArt-Sigma-for-webUI#4]
The readme says to install `diffusers>=0.28.1` which might lead to import errors for `SD3LoraLoaderMixin` after https://github.com/DenOfEquity/PixArt-Sigma-for-webUI/commit/8c28f3226b246c5b94e3c7b0c8f63e16869127f1

Can you update the readme to indicate `diffusers>=0.29.2` as the new minimum version?

**Comment by DenOfEquity** [comment]
Good catch, thanks.
I didn't get loras working, and forgot I'd experimented with adding the mixin. Updating requirements seems best approach, even though that extra stuff isn't used, because it might yet prove useful.
